apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hathor-full-node.fullname" . }}
spec:
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    {{- toYaml .Values.persistentVolumeClaim.resources | nindent 4 }}