# Default values for hathor-full-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

hathor:
  network: testnet
  # network: mainnet

  # Check https://github.com/HathorNetwork/hathor-core/blob/master/hathor/cli/run_node.py
  additionalOptions:
    cache:
      enabled: true
      size: '100000'
    xFastInitBeta: true
    walletIndex: true

statefulset:
  # You should avoid using more than 1 replica. The application is not prepared to handle concurrent access in the database.
  replicas: 1

image:
  repository: hathornetwork/hathor-core
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

envFrom: {}
  # - configMapRef:
  #     name: config-map-name
  # - secretRef:
  #     name: secret-name

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

persistentVolumeClaim:
  storageClassName: gp2
  resources:
    requests:
      storage: 30Gi

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
